### ISSUE TITLE
Comunicação do app com o back end

### ISSUE THREAD

**Issue by oliveiralex** [Jpoao/movieFlix-frontEnd-challenge#1]
Olá João Paulo, tudo bem?
Meu nome é Alexandre e estou corrigindo a sua atividade. Analisando a mesma, percebi que não foi incluído no seu projeto a aplicação back end para que o seu app se comunique. No caso, você deve usar o back end desenvolvido no cap 5.
Por gentileza, peço que você faça os ajustes e reenvie a atividade.

Abraço

**Comment by Jpoao** [comment]
Olá Alex, tudo sim, a parte de comunicação com o backend esta aqui: 

https://github.com/Jpoao/movieFlix-frontEnd-challenge/blob/main/src/util/requests.ts

**Comment by oliveiralex** [comment]
Olá João, me desculpa, agora que eu percebi que você usou a ideia de storage né? Você pode enviar novamente para que eu possa corrigir?
Obrigado!

**Comment by Jpoao** [comment]
Sim sim, tá tranquilo, já reenviei
